app_config:
  package_name: "stellar-harvest-ie-ml-stellar"
  docs_url: "https://www.swpc.noaa.gov/products/planetary-k-index"

model_cfg:
  test_size: 0.2
  random_state: 42
  n_estimators: 300
  max_depth: null

  # Time-series specifics
  resample_rule: "3h" # NOAA's native Kp cadence
  horizon: 1 # how many 3h-blocks ahead to predict
  lags: [ 1, 2, 3, 4, 8, 56, 216 ] # 3h, 6h, 9h, 12h, 24h, 1 week, 1 solar rotation

  # what comes from DB, used by validate.py
  input_features:
  - time_tag
  - kp_index
  - estimated_kp
  - kp

  target: estimated_kp # the float Kp; regression target
